---
title: "main"
author: "Tianqi Wang"
date: "12/9/2018"
output: html_document
---
```{r}
# The code below produces p_adj.png
source("p_adjust.R")
p <- 2^seq(-1, -7, by=-0.2)
p.adjust.M <- p.adjust.methods[(p.adjust.methods != "fdr")]
p.adj    <- sapply(p.adjust.M, function(meth) p.adjust(p, meth))

matplot(p, p.adj, ylab="p.adjust", type = "l", asp = 1, lty = 1:12,
        col = 1:12, main = "P-value adjustments", log="xy", xaxt="n", yaxt="n")
legend("bottomright", legend=colnames(p.adj),col=1:12,lty=1:12,cex=0.8, bty="n")
points(p,p, cex=1/4)

sfsmisc::eaxis(1)
sfsmisc::eaxis(2)

dev.copy(png,'p_adj.png')
dev.off()
```


```{r }
# The code below produces f2_indep_fdr.png
source("simulation.R")

cor <- 0
true_frac_vals <- c(0.75, 0.5, 0.25)
m_vals <- c(16, 64, 256)
mult.fig(mfrow=c(1,3), marP = -c(0,1.8,0,0))
res_indep_fdr_config_1 <- mult_sim(cor, true_frac_vals, m_vals,ret = "FDR", plot=TRUE, cex=0.8, ymax=0.055)
res_indep_fdr_config_1
```


```{r}
# The code below produces f3_indep_power.png

mult.fig(mfrow=c(1,3), marP = -c(0,1.8,0,0))
res_indep_power_config_1 <- mult_sim(cor, true_frac_vals, m_vals,ret = "Power", plot=TRUE, ymin = 0.4, ymax = 1, cex=0.8)
res_indep_power_config_1
```

```{r}
# The code below produces f4_indep_fdr.png
res_indep_fdr_config_2 <- mult_sim(cor, true_frac_vals, m_vals,ret = "FDR", mu_config = 2, plot = TRUE, ymax=0.052, cex=0.8)
res_indep_fdr_config_2
```

```{r}
# The code below produces f5_indep_power.png
res_indep_power_config_2 <- mult_sim(cor, true_frac_vals, m_vals,ret = "Power", mu_config = 2, plot = TRUE, ymin=0.02, ymax=0.75,cex=0.8)
res_indep_power_config_2
```

```{r}
# The code below produces mult_sim_fdr.png
mult.fig(mfrow=c(3,3), marP = -c(0,1.8,0,0))
m_vals <- c(8,16,32,64,128,256,512)
cor_vals <- c(0.25,0.5,0.75)
true_frac_vals <- c(0.25,0.5,0.75)
res_dep_fdr_config_2 <- mult_sim(cor_vals, true_frac_vals, m_vals,ret = c("FDR"), mu_config = 2, plot=TRUE)
```

```{r}
# The code below produces mult_sim_power.png
mult.fig(mfrow=c(3,3), marP = -c(0,1.8,0,0))
m_vals <- c(8,16,32,64,128,256,512)
cor_vals <- c(0.25,0.5,0.75)
true_frac_vals <- c(0.25,0.5,0.75)
res_dep_power_config_2 <- mult_sim(cor_vals, true_frac_vals, m_vals,ret = c("Power"), mu_config = 2, plot=TRUE, ymin=0., ymax=0.75)

```
